services:
  - type: web
    name: akin-world-web
    env: node
    plan: free   # change to 'starter' or higher if needed
    branch: main
    rootDir: backend
    buildCommand: |
      cd ../frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: AI_MUSIC_API_KEY
        sync: false   # set this in Render dashboard
